package org.firstinspires.ftc.teamcode;

public class TeleOpConstants {
    final static double LEFT_JOYSTICK_SPEED_ADJUSTER = 1.0;
    final static double RIGHT_JOYSTICK_SPEED_ADJUSTER = 1.0;
    final static double FLAP_SERVO_UP = 0.6844;
    final static double FLAP_SERVO_DOWN = 0.475;
    final static double BLANK = 0.000;
    final static double GREEN = 0.500;
    final static double VIOLET = 0.720;
    final static double RED = 0.280;
    final static double BLUE = 0.611;
    final static double ORANGE = 0.333;
    final static double SHORT_RANGE_VELOCITY = 1160;
    final static double MEDIUM_RANGE_VELOCITY = 1225;
    final static double LONG_RANGE_VELOCITY = 1275;
    final static double EXTRA_LONG_RANGE_VELOCITY = 1380;
    final static double AUTO_SHORT_RANGE_VELOCITY = 950;
    final static double AUTO_LONG_RANGE_VELOCITY = 1250;
    final static double MAX_VELOCITY = 2300.0;
    final static double VELOCITY_INCREMENT = 10.0;
    final static long SPINUP_MS = 2000;
    final static long FEED_MS = 1000;
    final static long FEED_SETTLE_MS = 150;
    final static double CELEBRATION_SPEED = 3500;
    final static int WAIT_FOR_MOTOR_OFFSET = 20;
    final static double kP = 60.0; // 7s: 18.0, 5s: 28.0, 3s: 34.0, 2.5s: 38.0, 2s: 44.0, 1.5s: 52.0, 1s: 60.0
    final static double kI = 0.000; // 7s: 0.15, 5s: 0.00, 3s: 0.005, 2.5s: 0.003, 2s: 0.002, 1.5s: 0.000, 1s: 0.000
    final static double kD = 26.5; // 7s: 7.5, 5s: 12.0, 3s: 13.0, 2.5s: 15.0, 2s: 17.0, 1.5s: 20.0, 1s: 24.0
    final static double kF = 32767 / TeleOpConstants.MAX_VELOCITY * 0.98; // 7s: *0.88, 5s: *0.92, 3s: *0.93, 2.5s: *0.94, 2s: *0.95, 1.5s: *0.965, 1s: *0.98
    final static double OPENCV_IMAGE_WIDTH = 1280;
    final static double OPENCV_IMAGE_HEIGHT = 720;
    final static double ALIGN_STRAFE_KP = 0.02;
    final static double ALIGN_STRAFE_KI = 0.0;
    final static double ALIGN_STRAFE_KD = 0.001;
    final static double ALIGN_TURN_KP = 0.01;
    final static double ALIGN_TURN_KI = 0.0;
    final static double ALIGN_TURN_KD = 0.0005;
    final static double ALIGN_FORWARD_KP = 0.04;
    final static double ALIGN_FORWARD_KI = 0.0;
    final static double ALIGN_FORWARD_KD = 0.001;
    final static double ALIGN_STRAFE_TOLERANCE_IN = 0.0;
    final static double ALIGN_BEARING_TOLERANCE_DEG = 0.0;
    final static double ALIGN_RANGE_TOLERANCE_IN = 0.0;
    final static double ALIGN_MAX_STRAFE_POWER = 0.35;
    final static double ALIGN_MAX_TURN_POWER = 0.25;
    final static double ALIGN_MAX_FORWARD_POWER = 0.35;
    final static double CAMERA_OFFSET_X_IN = 43.275 / 25.4;
    final static double CAMERA_OFFSET_Y_IN = 220.0 / 25.4;
    final static double ALIGN_EXTRA_LONG_RANGE_MIN_IN = 45;
    final static double ALIGN_EXTRA_LONG_RANGE_MAX_IN = 65;
    final static double ALIGN_LONG_RANGE_MIN_IN = 40;
    final static double ALIGN_LONG_RANGE_MAX_IN = 44.99;
    final static double ALIGN_MEDIUM_RANGE_MIN_IN = 30;
    final static double ALIGN_MEDIUM_RANGE_MAX_IN = 39.99;
    final static double ALIGN_TARGET_RANGE_EXTRA_LONG_IN = 50.0;
    public static double CAMERA_OFFSET_X_IN_RUNTIME = CAMERA_OFFSET_X_IN;
	final static double HEADING_KP = 15;
	final static double HEADING_KI = 0.0;
	final static double HEADING_KD = 60;
	final static double HEADING_MAX_TURN_POWER = 0.75;
	final static double HEADING_TOLERANCE_DEG = 0.5;
}
